name: autonomous_navigation_env
channels:
  - conda-forge
  - robostack-humble
dependencies:
  - python=3.11
  - cmake
  - colcon-common-extensions
  - ros-humble-ros-base
  - ros-humble-robot-state-publisher
  - ros-humble-joint-state-publisher
  - ros-humble-xacro
  - ros-humble-ros-gz
  - numpy
  - pyyaml
  - lxml
  - tinyxml2