# Docker Base Image
# https://hub.docker.com/layers/osrf/ros/humble-desktop-full/images/sha256-71ae08a6a0aae71a2f981e066c8a1d7dd76e956abf419c04626a0c746c3ebf4f
FROM osrf/ros:humble-desktop-full

# Make Work Space Directory
RUN mkdir -p /root/autonomous_navigation_ws/src
WORKDIR /root/autonomous_navigation_ws/src

# Install Dependencies