version: '3.8'

services:
  autonomous_navigation:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64 # M1 Mac에서는 Rosetta 2로 x86 이미지 실행
    container_name: autonomous_navigation_devcontainer
    tty: true
    stdin_open: true
    volumes:
      - ..:/root/autonomous_navigation_ws
    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=novnc:0.0   # RViz2 화면을 novnc 컨테이너로 출력
    networks:
      - x11

  novnc:
    image: theasp/novnc:latest
    container_name: autonomous_navigation_novnc
    environment:
      - DISPLAY_WIDTH=1728
      - DISPLAY_HEIGHT=972
    ports:
      - "8080:8080"   # 브라우저 접속 포트
    networks:
      - x11

networks:
  x11:
